language: php

php:
  - '7.0'
  - '5.6'

# Note: Code coverage requires php-xDebug extension enabled on CI server
install:
  - travis_retry composer install --no-interaction --no-suggest

before_script:
  - php -i

# Testing the app (see phpunit.xml) for configs, generating Code Coverage report
script:
  - composer test -- --coverage-clover=coverage.xml

#after_script:

after_success:
  # Submit coverage report to https://codecov.io
  - bash <(curl -s https://codecov.io/bash)